### ISSUE TITLE
FEATURE: Demo how to pass custom tailwind config

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#3]
see `MonacoTailwindcssOptions`

**Comment by remcohaszing** [comment]
The demo could add a new tab: _Tailwind config_.

This would render a model using the json language containing a Tailwind config. I’m deliberately mentioning JSON, not JavaScript, because that’s simpler for us to parse.

We could even contribute a JSON schema upstream in [https://github.com/SchemaStore/schemastore](JSON Schema Store), then use it in our demo.

**Comment by mhsdesign** [comment]
i guess we need https://github.com/remcohaszing/monaco-tailwindcss/issues/19 first
